### ISSUE TITLE
[Bug]: Trace is not re-activated after 10 minutes

### ISSUE THREAD

**Issue by fippu82** [dbeck121/CPI-Helper-Chrome-Extension#185]
**Describe the bug**
Wait for 10 minutes after setting the trace, it will not be set again (but the trace button text will still be red). 

**Additional context**
Seems bug got introduced with #167

**Comment by fippu82** [comment]
Fixed with #184

**Comment by santhoshvellingiri** [comment]
Hi @fippu82, Thanks for the wonderful extension!  I'm still facing this issue of trace not reactivated. Is the fix already available in the chrome store version?

**Comment by fippu82** [comment]
Hi @santhoshvellingiri , not yet, but it will be pushed to the stores very soon! Thanks for your patience.
